name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
assignees:
  - colbylwilliams
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
  - type: dropdown
    id: image
    attributes:
      label: What Image are you seeing the problem on?
      multiple: true
      options:
        - VS2022Box
        - VSCodeBox
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
