name: 'images action'
description: 'github action for building images'
author: 'colbylwilliams'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  secrets:
    description: foobar
    default: ${{ toJson(secrets) }}
    required: false
outputs:
  matrix:
    description: 'JSON string with a build matrix for packer build'
  build:
    description: 'true if there are any images to build in the matrix, otherwise false'
  gallery_name:
    description: 'The name of the Azure Compute Gallery'
  gallery_group:
    description: 'The resource group of the Azure Compute Gallery'
runs:
  using: 'node16'
  main: 'dist/index.js'
