name: Build Images

concurrency: ${{ github.ref }}

on:
  push:
    branches: [main]
    paths:
      - 'images/**'
      - 'scripts/**'

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.packer-definitions.outputs.build }}
      matrix: ${{ steps.packer-definitions.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: npm install js-yaml

      - name: Get Gallery Definition
        id: gallery-definitions
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/gallery.js');
            await script({github, context, core, glob, exec});

      - name: Get Image Definitions
        id: packer-definitions
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/images.js');
            await script({github, context, core, glob, exec});
        env:
          galleryName: ${{ steps.gallery-definitions.outputs.name }}
          galleryResourceGroup: ${{ steps.gallery-definitions.outputs.resourceGroup }}

  build:
    needs: prepare
    runs-on: ubuntu-latest
    # continue-on-error: true

    # this is needed to avoid workflow errors in case of an empty matrix
    if: ${{ needs.prepare.outputs.build == 'true' }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1.0.0

      - name: Build Image with Packer
        working-directory: ${{ matrix.source }}
        run: |

          # run packer to build the image
          packer build -force \
            -var "branch=${{ github.ref }}" \
            -var "commit=${{ github.sha }}" \
            -var "galleryName=${{ matrix.galleryName }}" \
            -var "galleryResourceGroup=${{ matrix.galleryResourceGroup }}" \
            -var "image=${{ matrix.name }}" \
            -var 'replicaLocations=${{ matrix.locations }}' \
            -var "location=${{ matrix.location }}" \
            -var "tempResourceGroup=${{ matrix.tempResourceGroup }}" \
            -var "buildResourceGroup=${{ matrix.buildResourceGroup }}" \
            -var "resolvedResourceGroup=${{ matrix.resolvedResourceGroup }}" \
            -var "subscription=$(az account show --query 'id' -o tsv)" \
            -var "version=${{ matrix.version }}" \
            . # <== run in the current folder

          exit $?

  cleanup:
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest

    # this is needed to avoid workflow errors in case of an empty matrix
    if: always() && ${{ needs.prepare.outputs.build == 'true' }}

    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Login to Azure
        if: ${{ matrix.tempResourceGroup != '' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Artifacts
        if: ${{ matrix.tempResourceGroup != '' }}
        run: az group delete -g "${{ matrix.tempResourceGroup }}" -y --no-wait || true
